version: "3.7"

networks:
  proxy:
    external: true
  internal:
    external: false
  localnet:
    external: true


services:
  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      KEYCLOAK_USER_FILE: /run/secrets/keycloak_user
      KEYCLOAK_PASSWORD_FILE: /run/secrets/keycloak_password
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_USER: keycloak
      DB_PASSWORD_FILE: /run/secrets/keycloak_db_password
      DB_PORT: 3307
      DB_DATABASE: keycloak
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_HOSTNAME: ${KEYCLOAK_URL}
#    volumes:
#      - ./import:/tmp/import
#    command:
      #- "-Dkeycloak.migration.action=import"
      #- "-Dkeycloak.migration.provider=dir"
      #- "-Dkeycloak.migration.dir=/tmp/import"
#      - ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]
    networks:
      - internal
#      - localnet
      - proxy
#    ports:
#      - 8080:8080
    secrets:
      - keycloak_user
      - keycloak_password
      - keycloak_db_password
    container_name: keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_URL}`)"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certresolver=lets-encrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.port=8080"
    depends_on:
      - keycloak-mysql

  keycloak-mysql:
    image: mysql:8.0.22
    container_name: keycloak-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/keycloak_db_root_password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD_FILE: /run/secrets/keycloak_db_password
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_HOST: '%'
    networks:
      - internal
      - localnet

    expose:
      - 3307

    labels:
      - traefik.enable=false
    volumes:
      - "${CONTAINER_PERSISTENT_VOLUME}/keycloak/mysql:/var/lib/mysql"
    secrets:
      - keycloak_db_root_password
      - keycloak_db_password

secrets:
  keycloak_db_password:
    file: "${CONTAINER_PERSISTENT_VOLUME}/secrets/keycloak_db_password.txt"
  keycloak_db_root_password:
    file: "${CONTAINER_PERSISTENT_VOLUME}/secrets/keycloak_db_root_password.txt"

  keycloak_user:
    file: "${CONTAINER_PERSISTENT_VOLUME}/secrets/keycloak_user.txt"
  keycloak_password:
    file: "${CONTAINER_PERSISTENT_VOLUME}/secrets/keycloak_password.txt"
