

networks:
  proxy:
    external: true
  default:
    driver: bridge

services:

  portainer-ce:
    image: portainer/portainer-ce:lts
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
#    ports:
#      - 8000:8000
#      - 9000:9000
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.united-portal.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls.certresolver=lets-encrypt"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.united-portal.com`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=lets-encrypt"

volumes:
  portainer_data:
    name: portainer_data
    external: false
