version: "3.3"

networks:
  proxy:
    external: true
  default:
    driver: bridge

services:

  portainer:
    image: portainer/portainer-ce:2.9.3
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.s001.thdi.ch`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=lets-encrypt"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.s001.thdi.ch`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=lets-encrypt"
    container_name: portainer
