version: "3.7"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  blog:
    image: wordpress:4.9.8-apache
    environment:
      WORDPRESS_DB_HOST: wordpress_mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.rule=Host(`${BLOG_URL}`)"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
    networks:
      - internal
      - proxy
    depends_on:
      - wordpress_mysql
    volumes:
      - "${CONTAINER_PERSISTENT_VOLUME}/wordpress/docker/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"
      - "${CONTAINER_PERSISTENT_VOLUME}/wordpress/data:/var/www/html" # Full wordpress project  -
    container_name: wordpress
    restart: unless-stopped
    secrets:
      - wordpress_db_password
  wordpress_mysql:
    image: mysql:5.7
    container_name: wordpress_mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/wordpress_db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password
    restart: unless-stopped
    networks:
      - internal
    labels:
      - traefik.enable=false
    volumes:
      - "${CONTAINER_PERSISTENT_VOLUME}/wordpress/mysql:/var/lib/mysql"
    secrets:
      - wordpress_db_root_password
      - wordpress_db_password

  phpmyadmin:
    image: phpmyadmin:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${DB_PHP_MYADMIN_URL}`)"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
    restart: unless-stopped
    networks:
      - internal
      - proxy
    environment:
      PMA_HOST: wordpress_mysql
      # PMA_USER: root
      # PMA_PASSWORD: /run/secrets/wordpress_db_root_password
    expose:
      - 80
    depends_on:
      - wordpress_mysql
    secrets:
      - wordpress_db_root_password

  adminer:
    image: adminer:4.6.3-standalone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.rule=Host(`${DBADMIN_URL}`)"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=lets-encrypt"
      - "traefik.port=8080"
    networks:
      - internal
      - proxy
    restart: unless-stopped
    depends_on:
      - wordpress_mysql
    environment:
      ADMINER_DEFAULT_SERVER: wordpress_mysql

secrets:
  wordpress_db_password:
    file: "${CONTAINER_PERSISTENT_VOLUME}/secrets/wordpress_db_password.txt"
  wordpress_db_root_password:
    file: "${CONTAINER_PERSISTENT_VOLUME}/secrets/wordpress_db_root_password.txt"
