version: "3.7"

networks:
  proxy:
    external: true
  internal:
    external: false
  localnet:
    external: true

services:
  blog:
    image: wordpress:4.9.8-apache
    environment:
      WORDPRESS_DB_HOST: wordpress-mysql
      # WORDPRESS_DB_HOST: docker-host
      # WORDPRESS_DB_HOST: $PRIVATE_IPV4
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.rule=Host(`${BLOG_URL}`)"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
    networks:
      - internal
      - localnet
      - proxy
    depends_on:
      - wordpress-mysql
    volumes:
      - "${CONTAINER_PERSISTENT_VOLUME}/wordpress/docker/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"
      - "${CONTAINER_PERSISTENT_VOLUME}/wordpress/data:/var/www/html" # Full wordpress project  -
    container_name: wordpress
    restart: unless-stopped
    secrets:
      - wordpress_db_password

  wordpress-mysql:
    image: mysql:5.7
    container_name: wordpress-mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/wordpress_db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password
      MYSQL_ROOT_HOST: '%'
    restart: unless-stopped
    networks:
      - internal
      - localnet
    labels:
      - traefik.enable=false
    volumes:
      - "${CONTAINER_PERSISTENT_VOLUME}/wordpress/mysql:/var/lib/mysql"
    secrets:
      - wordpress_db_root_password
      - wordpress_db_password


secrets:
  wordpress_db_password:
    file: "${CONTAINER_PERSISTENT_VOLUME}/secrets/wordpress_db_password.txt"
  wordpress_db_root_password:
    file: "${CONTAINER_PERSISTENT_VOLUME}/secrets/wordpress_db_root_password.txt"
