version: '3'


networks:
  proxy:
    external: true

services:

  todoh2:
    image: uportal/todo-app:latest
    labels:
      - traefik.http.routers.todoh2.rule=Host(`todo-h2.s001.thdi.ch`)
      - traefik.http.routers.todoh2.tls=true
      - traefik.http.routers.todoh2.tls.certresolver=lets-encrypt
      - traefik.port=8080
    restart: always
    networks:
      - proxy
    expose:
      - 8080
    environment:
      APP_NAME: Todo Rest with Spring Boot and H2
      ACTIVE_PROFILES: dev,h2
      APP_URL: https://todo-h2.s001.thdi.ch
    container_name: todoh2
