version: '3.7'

networks:
  proxy:
    external: true
  internal:
    external: false

services:

  traefik:
    image: traefik:v2.6.6
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
    container_name: traefik
    restart: always

  docker-host:
    image: qoomon/docker-host
    restart: unless-stopped
    container_name: docker-host
    cap_add: ["NET_ADMIN", "NET_RAW"]
    networks:
      - internal
