version: '3'

services:

  traefik:
    image: traefik:v2.6.6
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
    container_name: traefik
    restart: always

networks:
  proxy:
    external: true

