global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 10s
  external_labels:
    monitor: 'my-project'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          group: 'monitoring'
          application: 'prometheus'

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'traefik:8082' ]
        labels:
          group: 'reverse-proxy'
          application: 'traefik'

  - job_name: 'todo-h2-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'todoapp-on-h2:8080' ]
        labels:
          group: 'spring-boot'
          application: 'todo-h2'

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
        labels:
          group: 'host'
          application: 'cadvisor'

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          group: 'container'
          application: 'node-exporter'
