version: "3.7"

networks:
  proxy:
    external: true
  local:
    external: true

services:
  docker-host:
    image: qoomon/docker-host
    restart: unless-stopped
    container_name: docker-host
    cap_add: ["NET_ADMIN", "NET_RAW"]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
#      - traefik.http.routers.webmin-websecure.entrypoints=websecure
      - "traefik.http.routers.webmin-websecure.rule=Host(`${WEBMIN_URL}`)"
      - traefik.http.routers.webmin-websecure.tls=true
      - traefik.http.routers.webmin-websecure.tls.certresolver=lets-encrypt
      - traefik.http.services.docker-host.loadbalancer.server.port=10000

 #     - "traefik.port=10000"
    networks:
      - local
      - proxy
